let shopItemsDataInt = [
    {
      id: 1,
      name: "Chocolate Coconut Cake",
      price: 15,
      img: "pictures/Flourless-Chocolate-Coconut-Cake-3.jpg",
    },
    {
      id: 2,
      name: "Marshmallow Cake",
      price: 16,
      img: "pictures/delish-200827-marshmallow-cake-0004-landscape-ag-1598883971.jpg",
    },
    {
      id: 3,
      name: "Flourless Chocolate Cake",
      price: 12,
      img: "pictures/flourless-chocolate-cake-85892-1.jpeg",
    },
    {
      id: 4,
      name: "Chocolate Chip Cookie Tart",
      price: 18,
      img: "pictures/Chocolate_Chip_Cooke_Tart.jpeg",
    },
    {
        id: 5,
        name: "Peanut Butter Cheesecake",
        price: 17,
        img: "pictures/Peanut-Butter-Cheesecake-recipe-photo-0032.jpg",
    },
    {
        id: 6,
        name: "Turtle Cheesecake",
        price: 16,
        img: "pictures/Turtle-Cheesecake-Recipe-Card.jpg",
    },
    {
        id: 7,
        name: "Chocolate Custard Pie",
        price: 15,
        img: "pictures/ChocolateCustardPie.jpg",
    },
    {
        id: 8,
        name: "Keto Chocolate Cake",
        price: 19,
        img: "pictures/keto-cake-chocolate.jpg",
    },
    {
        id: 9,
        name: "Chocolate Chip Cookies",
        price: 15,
        img: "pictures/chocolate_chip_cookies.jpg",
    },
    {
        id: 10,
        name: "Potato Chip Cookies",
        price: 15,
        img: "pictures/potato-chip-cookies-3.jpg",
    },
    {
        id: 11,
        name: "Cannoli Cookies",
        price: 15,
        img: "pictures/cannoli-cookies1-1663332097.jpg",
    },
    {
        id: 12,
        name: "Chocolate Crunch Cookies",
        price: 15,
        img: "pictures/chocolate-peppermint-crunch-cookies.jpg",
    },
    {
        id: 13,
        name: "Panettone Cookies",
        price: 15,
        img: "pictures/panettone-cookies.jpg",
      },
      {
        id:14,
        name: "Hazelnut Cookies",
        price: 6,
        img: "pictures/Hazelnut-thumbprint.jpg",
      },
      {
        id: 15,
        name: "Fudgy Brownie Cookies",
        price: 15,
        img: "pictures/Fudgy-Brownie-Cookies-4.jpg",
      },
      {
        id: 16,
        name: "Twix Cookies",
        price: 19,
        img: "pictures/twix-cookies.jpg",
      },
      {
          id: 17,
          name: "Scotchmallows Candies",
          price: 11,
          img: "pictures/Scotchmallows.jpg",
        },
      {
          id: 18,
          name: "Dark Chocolate Almonds",
          price: 9,
          img: "pictures/almond-choco.jpg",
      },
      {
          id: 19,
          name: "Dark Brittle Candies",
          price: 11,
          img: "pictures/Brittle.jpg",
      },
      {
          id: 20,
          name: "Dark Marzipan",
          price: 11,
          img: "pictures/Dark-Marzipan.jpg",
      },
      {
          id: 21,
          name: "Dark Bordeaux",
          price: 11,
          img: "pictures/Dark-Bordeaux.jpg",
      },
      {
          id: 22,
          name: "Dark Salted Caramel",
          price: 11,
          img: "pictures/Salt-candies.jpg",
      },
      {
          id: 23,
          name: "Dark Buttchew Candies",
          price: 11,
          img: "pictures/butterchew.jpg",
      },
      {
          id: 24,
          name: "Dark Pecan Buds",
          price: 11,
          img: "pictures/dark-pecan-bud.jpg",
      },
      {
        id: 25,
        name: "Fantasy Fudge",
        price: 11,
        img: "pictures/fantasy-fudge.jpg",
    },
    {
        id: 26,
        name: "Chocolate Crinkle Cookies",
        price: 15,
        img: "pictures/Chocolate-Crinkle-Cookies-6.jpg",
    },
    {
        id: 27,
        name: "Strawberries in Chocolate",
        price: 11,
        img: "pictures/strawberries.webp",
    },
    {
        id: 28,
        name: "Chocoflan",
        price: 17,
        img: "pictures/Chocoflan.jpg",
    },
    {
        id: 29,
        name: "Profiteroles",
        price: 11,
        img: "pictures/profiteroles.jpeg",
    },
    {
        id: 30,
        name: "Millionaire Shortbread",
        price: 17,
        img: "pictures/millionaire_shortbread.jpg",
    },
    {
        id: 31,
        name: "Pudding",
        price: 8,
        img: "pictures/pudding.jpg",
    },
    {
        id: 32,
        name: "Oreo Cookie Balls",
        price: 10,
        img: "pictures/Oreo-Cookie-Balls.png",
    },
  ];
